/**
 * DailyReportStore - In-memory storage for JSON daily reports
 *
 * Stores daily reports generated by DailyReportGenerator and provides
 * retrieval methods for accessing historical data.
 */

class DailyReportStore {
  constructor() {
    // Map of day -> dailyReport (JSON object)
    this.reports = new Map();

    // Metadata about stored reports
    this.metadata = {
      totalReports: 0,
      oldestDay: null,
      newestDay: null,
      storageStats: {
        totalSize: 0, // Estimated size in bytes
        lastUpdated: null
      }
    };
  }

  /**
   * Store a daily report
   * @param {number} day - The day number
   * @param {object} report - The JSON daily report
   * @returns {boolean} Success
   */
  store(day, report) {
    try {
      if (!report || typeof report !== 'object') {
        throw new Error('Invalid report: must be a valid object');
      }

      if (typeof day !== 'number' || day < 1) {
        throw new Error('Invalid day: must be a positive number');
      }

      // Validate report structure (basic check)
      if (!report.day || !report.timestamp || !report.summary) {
        console.warn(`[DailyReportStore] Storing report with incomplete structure for day ${day}`);
      }

      // Store the report
      this.reports.set(day, {
        ...report,
        storedAt: Date.now(),
        size: this.estimateSize(report)
      });

      // Update metadata
      this.updateMetadata(day, report);

      console.log(`[DailyReportStore] Stored daily report for day ${day}`);
      return true;

    } catch (error) {
      console.error(`[DailyReportStore] Failed to store report for day ${day}:`, error.message);
      return false;
    }
  }

  /**
   * Retrieve a daily report by day
   * @param {number} day - The day number
   * @returns {object|null} The daily report or null if not found
   */
  get(day) {
    const stored = this.reports.get(day);
    return stored ? stored : null;
  }

  /**
   * Get all stored reports
   * @returns {Map} Map of day -> report
   */
  getAll() {
    return new Map(this.reports);
  }

  /**
   * Get all day numbers that have reports
   * @returns {number[]} Array of day numbers, sorted
   */
  getDays() {
    return Array.from(this.reports.keys()).sort((a, b) => a - b);
  }

  /**
   * Get the latest daily report
   * @returns {object|null} The most recent report or null if no reports
   */
  getLatest() {
    const days = this.getDays();
    if (days.length === 0) return null;

    return this.get(days[days.length - 1]);
  }

  /**
   * Get reports for a range of days
   * @param {number} startDay - Starting day (inclusive)
   * @param {number} endDay - Ending day (inclusive)
   * @returns {object[]} Array of reports for the specified days
   */
  getRange(startDay, endDay) {
    const reports = [];
    for (let day = startDay; day <= endDay; day++) {
      const report = this.get(day);
      if (report) {
        reports.push(report);
      }
    }
    return reports;
  }

  /**
   * Get reports from the last N days
   * @param {number} days - Number of recent days to retrieve
   * @returns {object[]} Array of the most recent reports
   */
  getRecent(days = 7) {
    const allDays = this.getDays();
    if (allDays.length === 0) return [];

    const startIndex = Math.max(0, allDays.length - days);
    const recentDays = allDays.slice(startIndex);

    return recentDays.map(day => this.get(day)).filter(Boolean);
  }

  /**
   * Clear all stored reports
   */
  clear() {
    this.reports.clear();
    this.metadata = {
      totalReports: 0,
      oldestDay: null,
      newestDay: null,
      storageStats: {
        totalSize: 0,
        lastUpdated: null
      }
    };
    console.log('[DailyReportStore] All reports cleared');
  }

  /**
   * Clear reports older than a certain day
   * @param {number} cutoffDay - Remove reports for days before this
   * @returns {number} Number of reports removed
   */
  clearOldReports(cutoffDay) {
    let removed = 0;
    for (const [day, report] of this.reports.entries()) {
      if (day < cutoffDay) {
        this.reports.delete(day);
        this.metadata.storageStats.totalSize -= report.size || 0;
        removed++;
      }
    }

    if (removed > 0) {
      this.updateMetadataAfterClear();
      console.log(`[DailyReportStore] Cleared ${removed} old reports (before day ${cutoffDay})`);
    }

    return removed;
  }

  /**
   * Get storage statistics
   * @returns {object} Storage statistics
   */
  getStats() {
    return {
      ...this.metadata,
      averageReportSize: this.metadata.totalReports > 0
        ? Math.round(this.metadata.storageStats.totalSize / this.metadata.totalReports)
        : 0,
      daysWithReports: this.getDays().length,
      dateRange: this.metadata.oldestDay && this.metadata.newestDay
        ? { from: this.metadata.oldestDay, to: this.metadata.newestDay }
        : null
    };
  }

  /**
   * Export all reports as JSON
   * @returns {object} Export object with all reports and metadata
   */
  export() {
    return {
      metadata: this.getStats(),
      reports: Object.fromEntries(this.reports),
      exportTimestamp: new Date().toISOString()
    };
  }

  /**
   * Import reports from exported data
   * @param {object} exportData - Exported data from export()
   * @returns {number} Number of reports imported
   */
  import(exportData) {
    let imported = 0;

    if (exportData.reports && typeof exportData.reports === 'object') {
      for (const [dayStr, report] of Object.entries(exportData.reports)) {
        const day = parseInt(dayStr, 10);
        if (!isNaN(day) && report) {
          this.store(day, report);
          imported++;
        }
      }
    }

    if (imported > 0) {
      console.log(`[DailyReportStore] Imported ${imported} reports`);
    }

    return imported;
  }

  /**
   * Update metadata after storing a report
   * @private
   */
  updateMetadata(day, report) {
    this.metadata.totalReports = this.reports.size;

    // Update day range
    if (this.metadata.oldestDay === null || day < this.metadata.oldestDay) {
      this.metadata.oldestDay = day;
    }
    if (this.metadata.newestDay === null || day > this.metadata.newestDay) {
      this.metadata.newestDay = day;
    }

    // Update storage stats
    this.metadata.storageStats.totalSize += report.size || this.estimateSize(report);
    this.metadata.storageStats.lastUpdated = Date.now();
  }

  /**
   * Update metadata after clearing reports
   * @private
   */
  updateMetadataAfterClear() {
    const days = this.getDays();

    this.metadata.totalReports = days.length;
    this.metadata.oldestDay = days.length > 0 ? days[0] : null;
    this.metadata.newestDay = days.length > 0 ? days[days.length - 1] : null;
    this.metadata.storageStats.lastUpdated = Date.now();
  }

  /**
   * Estimate the size of a report object in bytes
   * @private
   * @param {object} report - Report object
   * @returns {number} Estimated size in bytes
   */
  estimateSize(report) {
    try {
      // Simple estimation: JSON string length * 2 (for UTF-16 storage)
      const jsonString = JSON.stringify(report);
      return jsonString.length * 2;
    } catch (error) {
      // Fallback estimation based on object structure
      return this.estimateObjectSize(report);
    }
  }

  /**
   * Estimate object size recursively
   * @private
   * @param {any} obj - Object to estimate
   * @returns {number} Estimated size
   */
  estimateObjectSize(obj) {
    if (obj === null || obj === undefined) return 8;
    if (typeof obj === 'boolean') return 4;
    if (typeof obj === 'number') return 8;
    if (typeof obj === 'string') return obj.length * 2;
    if (typeof obj === 'object') {
      if (Array.isArray(obj)) {
        return 16 + obj.reduce((sum, item) => sum + this.estimateObjectSize(item), 0);
      } else {
        let size = 16; // Object overhead
        for (const [key, value] of Object.entries(obj)) {
          size += key.length * 2 + this.estimateObjectSize(value);
        }
        return size;
      }
    }
    return 8; // Default size
  }

  /**
   * Get a summary of reports for quick overview
   * @returns {object} Summary of all reports
   */
  getSummary() {
    const days = this.getDays();
    const summary = {
      totalDays: days.length,
      dayRange: days.length > 0 ? { first: days[0], last: days[days.length - 1] } : null,
      reports: [],
      totals: {
        totalErrors: 0,
        totalEvents: 0,
        totalIssues: 0
      }
    };

    for (const day of days) {
      const report = this.get(day);
      if (report) {
        const daySummary = {
          day: report.day,
          timestamp: report.timestamp,
          errors: report.errors?.totalErrors || 0,
          events: report.summary?.totalEvents || 0,
          issues: report.issues?.length || 0,
          dataCompleteness: report.metadata?.dataCompleteness?.percentage || 0
        };

        summary.reports.push(daySummary);
        summary.totals.totalErrors += daySummary.errors;
        summary.totals.totalEvents += daySummary.events;
        summary.totals.totalIssues += daySummary.issues;
      }
    }

    return summary;
  }
}

module.exports = DailyReportStore;